### ISSUE TITLE
IndexError if SELECT statement contains multiple user-defined variables

### ISSUE THREAD

**Issue by Naitreey** [dbcli/mycli#507] opened 2017-08-27 11:03 UTC
Hi,
I was trying to execute the following SQL statement:

```
SELECT @min_price:=MIN(price), @max_price:=MAX(price) FROM shop;
```
which crashes `mycli` with `IndexError`:

```
Traceback (most recent call last):
  File "/home/naitree/.pyenv/versions/3.6.2/bin/mycli", line 11, in <module>
    sys.exit(cli())
  File "/home/naitree/.pyenv/versions/3.6.2/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/naitree/.pyenv/versions/3.6.2/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/naitree/.pyenv/versions/3.6.2/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/naitree/.pyenv/versions/3.6.2/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/naitree/.pyenv/versions/3.6.2/lib/python3.6/site-packages/mycli/main.py", line 1009, in cli
    mycli.run_cli()
  File "/home/naitree/.pyenv/versions/3.6.2/lib/python3.6/site-packages/mycli/main.py", line 660, in run_cli
    one_iteration()
  File "/home/naitree/.pyenv/versions/3.6.2/lib/python3.6/site-packages/mycli/main.py", line 493, in one_iteration
    destroy = confirm_destructive_query(document.text)
  File "/home/naitree/.pyenv/versions/3.6.2/lib/python3.6/site-packages/mycli/main.py", line 1128, in confirm_destructive_query
    if is_destructive(queries) and sys.stdin.isatty():
  File "/home/naitree/.pyenv/versions/3.6.2/lib/python3.6/site-packages/mycli/main.py", line 1117, in is_destructive
    return queries_start_with(queries, keywords)
  File "/home/naitree/.pyenv/versions/3.6.2/lib/python3.6/site-packages/mycli/main.py", line 1111, in queries_start_with
    if query and query_starts_with(query, prefixes) is True:
  File "/home/naitree/.pyenv/versions/3.6.2/lib/python3.6/site-packages/mycli/main.py", line 1105, in query_starts_with
    formatted_sql = sqlparse.format(query.lower(), strip_comments=True)
  File "/home/naitree/.pyenv/versions/3.6.2/lib/python3.6/site-packages/sqlparse/__init__.py", line 60, in format
    return u''.join(stack.run(sql, encoding))
  File "/home/naitree/.pyenv/versions/3.6.2/lib/python3.6/site-packages/sqlparse/engine/filter_stack.py", line 36, in run
    stmt = grouping.group(stmt)
  File "/home/naitree/.pyenv/versions/3.6.2/lib/python3.6/site-packages/sqlparse/engine/grouping.py", line 357, in group
    func(stmt)
  File "/home/naitree/.pyenv/versions/3.6.2/lib/python3.6/site-packages/sqlparse/engine/grouping.py", line 146, in group_assignment
    _group(tlist, sql.Assignment, match, valid_prev, valid_next, post)
  File "/home/naitree/.pyenv/versions/3.6.2/lib/python3.6/site-packages/sqlparse/engine/grouping.py", line 385, in _group
    grp = tlist.group_tokens(cls, from_idx, to_idx, extend=extend)
  File "/home/naitree/.pyenv/versions/3.6.2/lib/python3.6/site-packages/sqlparse/sql.py", line 287, in group_tokens
    start = self.tokens[start_idx]
IndexError: list index out of range
```

It seems like a tokenization error.

Using `mycli` version `1.12.1`.

I've tried if the above sql is reduced using a single user-defined variable, nothing bad happens:

```
SELECT @min_price:=MIN(price) from shop;
```

Any thought on this? Thanks.

**Comment by j-bennet** [comment] 2017-08-27 23:51
Hi @Naitreey , what's your version of sqlparse?

**Comment by Naitreey** [comment] 2017-08-29 11:14
Hi @j-bennet , sqlparse version is 0.2.3.

**Comment by j-bennet** [comment] 2017-08-29 15:43
Hmm, that's confusing. I just created a new venv with the same setup as yours and pip-installed `mycli` in there, and there's no such problem:

```
(mycli36) --- ~ » python --version
Python 3.6.2
(mycli36) --- ~ » pip freeze | grep sqlparse
sqlparse==0.2.3
```

the query returns fine:

```
Version: 1.12.1
mysql root@localhost:test> select @minx:=min(x), @maxx:=max(x) from a
+-----------------+-----------------+
| @minx:=min(x)   | @maxx:=max(x)   |
|-----------------+-----------------|
| 1               | 1000000         |
+-----------------+-----------------+
1 row in set
Time: 0.007s
```

I'm wondering if it's something related to locale settings. What's the output of `locale` command on your machine? Here's mine:

```
(mycli36) --- ~ » locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

@tsroten Would you have some ideas?

**Comment by tsroten** [comment] 2017-08-29 15:47
Well, I was able to reproduce this. Very odd. It was in the middle of typing the SQL statement for me. Mycli immediately crashes with the stack trace above. I'll see if I can dig through it and see what's happening. Not sure yet if this is an issue with Mycli or sqlparse.

**Comment by Naitreey** [comment] 2017-08-29 16:31
@j-bennet Here is my `locale`:

```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_HK.UTF-8
LC_TIME=en_HK.UTF-8
LC_COLLATE=C
LC_MONETARY=en_HK.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_HK.UTF-8
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT=en_HK.UTF-8
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

@tsroten Yeah, same here. Just copy & paste the statement into Mycli, move cursor right pass the `,` at the middle of it, hit `<space>`, then Mycli crashes.

**Comment by tsroten** [comment] 2017-09-23 03:02
This only appears to happen with the semi-colon. The problem is with sqlparse. I can reproduce it by doing:
```python
import sqlparse
sqlparse.parse('SELECT @min_price:=MIN(price), @max_price:=MAX(price) FROM shop;')
IndexError: list index out of range
```

I don't know how to fix it, though. If anyone has time to dig into sqlparse, that would be helpful.

**Comment by Terseus** [comment] 2017-09-23 10:45
After some testing I'm convinced that the bug comes from sqlparse, not from mycli.

I've opened an issue in sqlparse: https://github.com/andialbrecht/sqlparse/issues/359

The bug is quite curious, in `sqlparse.format` only happens when `strip_comments=True` is used **and** the statement ends in a semicolon (@j-bennet:  I think that's why you had problems reproducing it).

As a temporary workaround we may strip the semicolon before calling `sqlparse.format` or call it without `strip_comments=True` (if that's possible).

I think we may wait to see if sqlparse fix the bug, and if after a while they dont't/can't fix it we may apply some of the workarounds.

**Comment by tsroten** [comment] 2017-09-24 13:08
It looks like the folks over at sqlparse fixed this bug on their end. It will be in the next sqlparse release, which they're planning to push out next week.

**Comment by tsroten** [comment] 2017-11-27 18:02
sqlparse 0.2.4 was released in September, so I'm going to close this issue now.

**Closed by tsroten** 2017-11-27 18:02 UTC
Labels: blocked, bug
