### ISSUE TITLE
Why do I enter the code? Please help me

### ISSUE THREAD

**Issue by LHY1113** [dbcli/mycli#972] opened 2021-03-12 04:58 UTC
C:\WINDOWS\system32>mycli -uroot -p123456
Traceback (most recent call last):
  File "e:\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "e:\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Python\Python39\Scripts\mycli.exe\__main__.py", line 4, in <module>
  File "e:\python\python39\lib\site-packages\mycli\main.py", line 41, in <module>
    from .sqlexecute import FIELD_TYPES, SQLExecute
  File "e:\python\python39\lib\site-packages\mycli\sqlexecute.py", line 6, in <module>
    from pymysql.converters import (convert_mysql_timestamp, convert_datetime,
ImportError: cannot import name 'convert_mysql_timestamp' from 'pymysql.converters' (e:\python\python39\lib\site-packages\pymysql\converters.py)

C:\WINDOWS\system32> (e:\python\python39\lib\site-packages\pymysql\converters.py)

C:\WINDOWS\system32>mycli
Traceback (most recent call last):
  File "e:\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "e:\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Python\Python39\Scripts\mycli.exe\__main__.py", line 4, in <module>
  File "e:\python\python39\lib\site-packages\mycli\main.py", line 41, in <module>
    from .sqlexecute import FIELD_TYPES, SQLExecute
  File "e:\python\python39\lib\site-packages\mycli\sqlexecute.py", line 6, in <module>
    from pymysql.converters import (convert_mysql_timestamp, convert_datetime,
ImportError: cannot import name 'convert_mysql_timestamp' from 'pymysql.converters' (e:\python\python39\lib\site-packages\pymysql\converters.py)

C:\WINDOWS\system32>mycli
'mycli' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\WINDOWS\system32>pip3 install mycli
Collecting mycli
  Using cached mycli-1.24.1-py2.py3-none-any.whl (96 kB)
Requirement already satisfied: importlib-resources>=5.0.0 in e:\python\python39\lib\site-packages (from mycli) (5.1.2)
Requirement already satisfied: pyaes>=1.6.1 in e:\python\python39\lib\site-packages (from mycli) (1.6.1)
Requirement already satisfied: sqlparse<0.4.0,>=0.3.0 in e:\python\python39\lib\site-packages (from mycli) (0.3.1)
Requirement already satisfied: Pygments>=1.6 in e:\python\python39\lib\site-packages (from mycli) (2.8.1)
Requirement already satisfied: configobj>=5.0.5 in e:\python\python39\lib\site-packages (from mycli) (5.0.6)
Requirement already satisfied: cryptography>=1.0.0 in e:\python\python39\lib\site-packages (from mycli) (3.4.6)
Requirement already satisfied: click>=7.0 in e:\python\python39\lib\site-packages (from mycli) (7.1.2)
Requirement already satisfied: PyMySQL>=0.9.2 in e:\python\python39\lib\site-packages (from mycli) (1.0.2)
Requirement already satisfied: pyperclip>=1.8.1 in e:\python\python39\lib\site-packages (from mycli) (1.8.2)
Requirement already satisfied: prompt-toolkit<4.0.0,>=3.0.6 in e:\python\python39\lib\site-packages (from mycli) (3.0.17)
Requirement already satisfied: cli-helpers[styles]>=2.0.1 in e:\python\python39\lib\site-packages (from mycli) (2.1.0)
Requirement already satisfied: tabulate[widechars]>=0.8.2 in e:\python\python39\lib\site-packages (from cli-helpers[styles]>=2.0.1->mycli) (0.8.9)
Requirement already satisfied: terminaltables>=3.0.0 in e:\python\python39\lib\site-packages (from cli-helpers[styles]>=2.0.1->mycli) (3.1.0)
Requirement already satisfied: six in e:\python\python39\lib\site-packages (from configobj>=5.0.5->mycli) (1.15.0)
Requirement already satisfied: cffi>=1.12 in e:\python\python39\lib\site-packages (from cryptography>=1.0.0->mycli) (1.14.5)
Requirement already satisfied: pycparser in e:\python\python39\lib\site-packages (from cffi>=1.12->cryptography>=1.0.0->mycli) (2.20)
Requirement already satisfied: wcwidth in e:\python\python39\lib\site-packages (from prompt-toolkit<4.0.0,>=3.0.6->mycli) (0.2.5)
Installing collected packages: mycli
Successfully installed mycli-1.24.1

C:\WINDOWS\system32>mycli -uroot -p123456
Traceback (most recent call last):
  File "e:\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "e:\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Python\Python39\Scripts\mycli.exe\__main__.py", line 7, in <module>
  File "e:\python\python39\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "e:\python\python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "e:\python\python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "e:\python\python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "e:\python\python39\lib\site-packages\mycli\main.py", line 1160, in cli
    mycli = MyCli(prompt=prompt, logfile=logfile,
  File "e:\python\python39\lib\site-packages\mycli\main.py", line 136, in __init__
    c = self.config = read_config_files(config_files)
  File "e:\python\python39\lib\site-packages\mycli\config.py", line 105, in read_config_files
    _config = read_config_file(_file, list_values=list_values)
  File "e:\python\python39\lib\site-packages\mycli\config.py", line 52, in read_config_file
    config = ConfigObj(f, interpolation=False, encoding='utf8',
  File "e:\python\python39\lib\site-packages\configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "e:\python\python39\lib\site-packages\configobj.py", line 1287, in _load
    content = self._handle_bom(content)
  File "e:\python\python39\lib\site-packages\configobj.py", line 1437, in _handle_bom
    return self._decode(infile, self.encoding)
  File "e:\python\python39\lib\site-packages\configobj.py", line 1517, in _decode
    infile[i] = line.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa8 in position 52: invalid start byte

C:\WINDOWS\system32>mycli
Traceback (most recent call last):
  File "e:\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "e:\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Python\Python39\Scripts\mycli.exe\__main__.py", line 7, in <module>
  File "e:\python\python39\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "e:\python\python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "e:\python\python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "e:\python\python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "e:\python\python39\lib\site-packages\mycli\main.py", line 1160, in cli
    mycli = MyCli(prompt=prompt, logfile=logfile,
  File "e:\python\python39\lib\site-packages\mycli\main.py", line 136, in __init__
    c = self.config = read_config_files(config_files)
  File "e:\python\python39\lib\site-packages\mycli\config.py", line 105, in read_config_files
    _config = read_config_file(_file, list_values=list_values)
  File "e:\python\python39\lib\site-packages\mycli\config.py", line 52, in read_config_file
    config = ConfigObj(f, interpolation=False, encoding='utf8',
  File "e:\python\python39\lib\site-packages\configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "e:\python\python39\lib\site-packages\configobj.py", line 1287, in _load
    content = self._handle_bom(content)
  File "e:\python\python39\lib\site-packages\configobj.py", line 1437, in _handle_bom
    return self._decode(infile, self.encoding)
  File "e:\python\python39\lib\site-packages\configobj.py", line 1517, in _decode
    infile[i] = line.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa8 in position 52: invalid start byte

**Comment by ShreeyansB** [comment] 2021-04-18 11:37
I am facing a similar error on Windows 10 too

>  mycli -u root -h localhost -p pass --database test
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ballistic Swami\AppData\Roaming\Python\Python39\Scripts\mycli.exe\__main__.py", line 7, in <module>
  File "C:\Users\Ballistic Swami\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Ballistic Swami\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\Ballistic Swami\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Ballistic Swami\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Ballistic Swami\AppData\Roaming\Python\Python39\site-packages\mycli\main.py", line 1160, in cli
    mycli = MyCli(prompt=prompt, logfile=logfile,
  File "C:\Users\Ballistic Swami\AppData\Roaming\Python\Python39\site-packages\mycli\main.py", line 136, in __init__
    c = self.config = read_config_files(config_files)
  File "C:\Users\Ballistic Swami\AppData\Roaming\Python\Python39\site-packages\mycli\config.py", line 105, in read_config_files
    _config = read_config_file(_file, list_values=list_values)
  File "C:\Users\Ballistic Swami\AppData\Roaming\Python\Python39\site-packages\mycli\config.py", line 52, in read_config_file
    config = ConfigObj(f, interpolation=False, encoding='utf8',
  File "C:\Users\Ballistic Swami\AppData\Roaming\Python\Python39\site-packages\configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "C:\Users\Ballistic Swami\AppData\Roaming\Python\Python39\site-packages\configobj.py", line 1287, in _load
    content = self._handle_bom(content)
  File "C:\Users\Ballistic Swami\AppData\Roaming\Python\Python39\site-packages\configobj.py", line 1437, in _handle_bom
    return self._decode(infile, self.encoding)
  File "C:\Users\Ballistic Swami\AppData\Roaming\Python\Python39\site-packages\configobj.py", line 1517, in _decode
    infile[i] = line.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 52: invalid start byte

**Comment by amjith** [comment] 2021-05-09 03:30
Duplicate of #978

**Closed by amjith** 2021-05-09 03:30 UTC
