### ISSUE TITLE
mycli crashes with pymysql 0.6.2

### ISSUE THREAD

**Issue by lhw** [dbcli/mycli#155] opened 2015-09-21 10:25 UTC
The bug which caused the crash with `pymysql 0.6.2` (#83) still exists. `pymysql 0.6.6` only handles it gracefully. ConfigObj is unable to parse the MySQL config files. Which later on caused a crash with pymysql not handling an empty field/fields correctly. Version here is `mycli 1.4.0`
```
2015-09-21 12:58:51,768 (17883/MainThread) mycli DEBUG - Initializing mycli logging.
2015-09-21 12:58:51,769 (17883/MainThread) mycli DEBUG - Log file '~/.mycli.log'.
2015-09-21 12:58:51,770 (17883/MainThread) mycli.main ERROR - Error parsing u'/etc/mysql/my.cnf'.
2015-09-21 12:58:51,770 (17883/MainThread) mycli.main ERROR - Recovering partially parsed config values.
2015-09-21 12:58:51,772 (17883/MainThread) mycli.main ERROR - Error parsing u'/etc/mysql/my.cnf'.
2015-09-21 12:58:51,772 (17883/MainThread) mycli.main ERROR - Recovering partially parsed config values.
2015-09-21 12:58:51,773 (17883/MainThread) mycli.sqlexecute DEBUG - Connection DB Params: 
        database: None  user: u'root'   host: u'localhost'      port: 3306      socket: '/var/run/mysqld/mysqld.sock'   charset: u'utf8'
2015-09-21 12:58:54,534 (17883/MainThread) mycli.sqlexecute DEBUG - Connection DB Params: 
        database: None  user: u'root'   host: u'localhost'      port: 3306      socket: '/var/run/mysqld/mysqld.sock'   charset: u'utf8'
2015-09-21 12:58:54,537 (17883/MainThread) mycli.main DEBUG - Launch Params: 
        database: None  user: u'root'   host: None      port: None
2015-09-21 12:58:54,537 (17883/MainThread) mycli.main DEBUG - Original value for LESS env var: '-R'
2015-09-21 12:58:54,540 (17883/MainThread) mycli.main ERROR - Error parsing u'/etc/mysql/my.cnf'.
2015-09-21 12:58:54,540 (17883/MainThread) mycli.main ERROR - Recovering partially parsed config values.

```
My current config is basically the standard MariaDB config, I put them up in a gist here: https://gist.github.com/lhw/c4893fe72f9141129357

Apparently ConfigObj is not able to parse lines which have no assignment. Like `skip-external-locking`
```python
>>> from configobj import ConfigObj
>>> c = ConfigObj("/etc/mysql/my.cnf")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "/usr/lib/python2.7/dist-packages/configobj.py", line 1318, in _load
    raise error
configobj.ConfigObjError: Parsing failed with several errors.
First error at line 43.
```
There is a seven year old mailing list thread about it on [sourceforge](http://sourceforge.net/p/configobj/mailman/message/18644998/).
I assume nobody ever took the time to actually implement it.

**Comment by tsroten** [comment] 2015-09-21 13:11
I'm surprised ConfigObj doesn't support this. Would assigning it a boolean value be a possible workaround? Boolean values are [permitted values for `skip-external-locking`](https://dev.mysql.com/doc/refman/5.0/en/server-system-variables.html#sysvar_skip_external_locking).

**Comment by lhw** [comment] 2015-09-21 14:00
Yes it does indeed work. I tested it earlier. It's basically just a short form for `skip-external-locking = on`. I think writting a simple extended validator for ConfigObj might work.

**Comment by tsroten** [comment] 2015-09-22 01:35
Hmm, [it doesn't appear to be that easy](http://configobj.readthedocs.org/en/latest/configobj.html#validation).

> Validation can perform two different operations :

> 1. Check that a value meets a specification. For example, check that a value is an integer between one and six, or is a choice from a specific set of options.

> 2. It can convert the value into the type required. For example, if one of your values is a port number, validation will turn it into an integer for you.

It looks to me like validation is for validating a value, not parsing the actual config file. The logic that creates the error you see above is built into the `ConfigObj` class. So, we would actually need to extend the entire class.

[Here](https://github.com/DiffSK/configobj/blob/master/src/configobj/__init__.py#L1075) is the regular expression object that makes `ConfigObj` throw an error at your config file. It is used in the [`ConfigObj._parse()` method](https://github.com/DiffSK/configobj/blob/master/src/configobj/__init__.py#L1544).

I don't see an easy way to make mycli's `ConfigObj` work with the full spectrum of MySQL option files. It seems like the simplest solution is to be slightly more verbose in your option file.

I wonder if the ConfigObj project would be open to this feature now?

What are your thoughts @amjith?

**Comment by amjith** [comment] 2015-09-22 02:30
@tsroten Thank you for digging into this. You're both right that ConfigObj doesn't parse a line that is not in the format of `key = value`. But I thought it would skip over those errors and continue parsing the file to the end. This is a snippet from their docs: 

```
Behaviour when parsing a config file depends on the option raise_errors. If ConfigObj encounters an error while parsing a config file:

If raise_errors=True then ConfigObj will raise the appropriate error and parsing will stop.

If raise_errors=False (the default) then parsing will continue to the end and all errors will be collected.
```

So I'd like to understand the issue here. 

@lhw You said the pymysql crashed later because of empty values, can you tell me what you mean by that? 

It seems like the lines you had copied from the log files show there is a valid value for all the args: 

```
2015-09-21 12:58:54,534 (17883/MainThread) mycli.sqlexecute DEBUG - Connection DB Params: 
        database: None  user: u'root'   host: u'localhost'      port: 3306      socket: '/var/run/mysqld/mysqld.sock'   charset: u'utf8'
```

So I don't understand how this caused a crash. I haven't tried your config file yet, I'll do it in an hour or two, but if you have more info, I'd appreciate it. 

@tsroten I'm open to sending a PR to ConfigObj to handle this case or if they're not responsive, I'm open to forking the project and vendoring the files in the packages folder. But I'd use that as a last option. I'd prefer not to diverge from the mainline of upstream libraries.

**Comment by lhw** [comment] 2015-09-22 06:53
Your conclusion is probably correct. Even in case ConfigObj does fail to completely read the config file it should still work according to the debug log.
Here is the actual error:
```python
lhw:~ % mycli -uroot  
Password: 
Traceback (most recent call last):
  File "/usr/bin/mycli", line 9, in <module>
    load_entry_point('mycli==1.4.0', 'console_scripts', 'console')()
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/share/mycli/mycli/main.py", line 592, in cli
    mycli.run_cli()
  File "/usr/share/mycli/mycli/main.py", line 301, in run_cli
    self.initialize_completions()
  File "/usr/share/mycli/mycli/main.py", line 500, in initialize_completions
    completer.extend_show_items(self.sqlexecute.show_candidates())
  File "/usr/share/mycli/mycli/sqlcompleter.py", line 104, in extend_show_items
    for show_item in show_items:
  File "/usr/share/mycli/mycli/sqlexecute.py", line 169, in show_candidates
    with self.conn.cursor() as cur:
AttributeError: __exit__
Exception AttributeError: "'NoneType' object has no attribute 'pack'" in <bound method Connection.__del__ of <pymysql.connections.Connection object at 0x7ffbdc5c2a90>> ignored
```

**Comment by amjith** [comment] 2015-09-22 15:04
@lhw The error you've pasted above points to the connection object being stale. Also the show_candidates() is the first query we make to the database to populate the completion values that come after the `SHOW` keyword. So clearly the connection object is bad which caused the crash when we tried to use it for the first time.

Can you try this experiment in a Python repl? 

```
>>> import pymysql
>>> c = pymysql.connect(database=None, user='root', host='localhost')
>>> cur = c.cursor()
>>> cur.execute('SELECT name from mysql.help_topic WHERE name like "SHOW %"')
```
That is executing the exact same query that mycli executes but without a context manager. 

I'm hoping that will give us a clue to why this is failing from mycli. 

If that works for you can you try downgrading pymysql to 0.6.2, you can downgrade using pip as follows: 

```
pip install pymysql==0.6.2
```

Try running mycli after downgrading pymysql. 

Unfortunately I'm unable to reproduce this bug on my computer, so I suspect there is something different with the database itself.

**Comment by tsroten** [comment] 2015-09-23 03:03
I requested the optional value feature on the ConfigObj project, https://github.com/DiffSK/configobj/issues/95. Another option if that doesn't pan out is using the built-in `configparser`, which does support optional values (it assigns them a value of `None`, which could be easily changed to `True` if needed).

**Comment by lhw** [comment] 2015-09-23 07:06
The query does work fine with pymysql 0.6.2
```python
>>> import pymysql
>>> c = pymysql.connect(database=None, user='root', host='localhost', passwd='*********')
>>> cur = c.cursor()
>>> cur.execute('SELECT name from mysql.help_topic WHERE name like "SHOW %"')
41
```

**Comment by tsroten** [comment] 2015-09-23 15:18
@amjith It looks like pymysql < 0.6.6 does not fully support using `Cursor` in a `with` statement. The `__enter__` and `__exit__` magic methods were [added to `Cursor` in 0.6.6](https://github.com/PyMySQL/PyMySQL/commit/bd29e7ef968ec82774cc869c60a1e9c9809e6f51).

**Comment by amjith** [comment] 2015-09-23 16:24
Aha. I was indeed confused. I think I'm with you guys now. :)

So the problem is, mycli won't work with Pymysql 0.6.2 but 0.6.2 is the only version available in debian as a deb package. That is unfortunate.

We rely on context managers quite a bit and I'm not sure it is worth rewriting pieces of mycli to accommodate older versions of pymysql. What will it take to update the debian package of pymysql to 0.6.6?

**Comment by tsroten** [comment] 2015-09-23 16:46
I have no idea how easy/hard it is to get Debian to add newer packages to their repositories.

Potentially, another option is to create a `cursor.py`:
```python
import pymysql

Cursor = pymysql.cursors.Cursor

if pymysql.VERSION[1] == 6 and pymysql.VERSION[2] < 6:
    class Cursor(pymysql.cursors.Cursor):
        
        def __enter__(self):
            return self
        
        def __exit__(self, *exc_info):
            del exc_info
            self.close()
```

Then, we'd change `mycli.sqlexecute`:
```python
from cursor import Cursor


conn = pymysql.connect(database=db, user=user, password=password,
                       host=host, port=port, unix_socket=socket,
                       use_unicode=True, charset=charset, autocommit=True,
                       client_flag=pymysql.constants.CLIENT.INTERACTIVE,
                       cursorclass=Cursor)
```

We would have to run some tests, but it looks like those are the only changes needed to make `Cursor` support the `with` statement. @amjith What do you think? Any idea how easy it would be to get Debian to add a newer version of pymysql to their repositories?

**Comment by amjith** [comment] 2015-09-23 17:03
@tsroten If you think the change is simple enough, go ahead and make a PR and I'll test the heck out of it and merge it in. 

I don't know how long it takes to update debian repos, @lhw might know the answer to that.

**Comment by lhw** [comment] 2015-09-23 18:50
Hm yeah I found those yesterday but I was sure I found the with operator functions in my file. Must have had 0.6.6 still installed. My bad.

@tsroten I opened a bug report on python-pymysql in debian for the update ([bugs.debian.org](http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=799776)). But depending on the maintainer it might take from a few days to months for an answer. It might be easier to get those two small functions in as a pymysql patch so the maintainer doesn't have to care about compatibility.

**Comment by lhw** [comment] 2015-09-23 19:42
I added it as a patch to my package for now. So you won't need to include in the repository [debian/patches/pymsql-0.6.2-compat.patch](https://github.com/lhw/debian-mycli/blob/master/debian/patches/pymsql-0.6.2-compat.patch).

One error still remains. On close the __del__ still tries pack method on None.
```
lhw:~ % mycli -uroot
Password:
Version: 1.4.0
mysql root@localhost:(none)> use mysql
You are now connected to database "mysql" as user "root"
Command Time: 0.000s
Format Time: 0.000s
mysql root@localhost:mysql>
Goodbye!
Exception AttributeError: "'NoneType' object has no attribute 'pack'" in <bound method Connection.__del__ of <pymysql.connections.Connection object at 0x7f201c20cad0>> ignored
```

**Comment by tsroten** [comment] 2015-09-23 20:35
Here are two versions of the method `pymysql.connections.Connection.__del__`. The first is from 6.6.2 and the second is from the current `master` branch.

Version 6.6.2:
```python
    def __del__(self):
        if self.socket:
            self.close()
```

Current master:
```python
    def __del__(self):
        if self.socket:
            try:
                self.socket.close()
            except:
                pass
        self.socket = None
        self._rfile = None
```

You might want to create a patch that subclasses `pymysql.connections.Connection` and overwrites the `__del__()` magic method to look like the second so it handles the errors gracefully. That would be similar to what we did for `pymysql.cursors.Cursor`.

Then, you'll need to change the function that mycli calls to initiate a connection (in `mycli.sqlexecute`). The current function call is to `pymysql.connect()`, which points to the `pymysql.Connect()` function:
```python
def Connect(*args, **kwargs):
    """
    Connect to the database; see connections.Connection.__init__() for
    more information.
    """
    from .connections import Connection
    return Connection(*args, **kwargs)
```
You can see it is returning an instance of `pymysql.connections.Connection`, when you'll want it to return your custom version of that class.

If you need help, let me know and I'll show you some sample code.

**Comment by amjith** [comment] 2015-09-24 00:09
Should we roll this into mycli master so @lhw doesn't have to patch it in his version?

**Comment by tsroten** [comment] 2015-09-24 01:03
@amjith Sure. Loosening up the pymysql version dependency would be nice. I'll work on it.

**Comment by tsroten** [comment] 2015-09-24 02:16
@amjith I've added all of the above changes into the [`issue_155` branch](https://github.com/dbcli/mycli/tree/issue_155).

@lhw If you could test it on your system using PyMySQL 0.6.2, that would be great. Let me know what errors, if any, you get. I still can't replicate your `Exception AttributeError: "'NoneType' object has no attribute 'pack'"[...]` error.

**Comment by lhw** [comment] 2015-09-24 11:29
I added your graceful exit patch to the package. It now works completely fine on debian/unstable. There don't seem to be any issues with prompt_toolkit 0.50 either. Same as pgcli.

You can check out the from (https://github.com/lhw/debian-mycli)[lhw/debian-mycli]. You can build it with git-buildpackage or dpkg-buildpackage. Package dependencies are all based on unstable packages. So you need them in your apt sources for dependency resolution.

**Comment by amjith** [comment] 2015-09-25 05:51
This is now fixed in master. We'll release a new version soon.

**Closed by amjith** 2015-09-25 05:51 UTC
Labels: bug, in progress
