### ISSUE TITLE
mycli 系统找不到指定的文件。

### ISSUE THREAD

**Issue by yuxingchang** [dbcli/mycli#841] opened 2020-04-05 14:48 UTC
**mycli in windows:**

mysql root@localhost:(none)> use mysql
You are now connected to database "mysql" as user "root"
Time: 0.001s
mysql root@localhost:mysql> show tables;
系统找不到指定的文件。
33 rows in set
Time: 0.012s
mysql root@localhost:mysql>

**Comment by luojianet** [comment] 2020-04-10 02:44
have same problem

**Comment by amjith** [comment] 2020-04-17 20:59
@yuxingchang Can you paste the contents of your log file? 

You can find them under `C:\Users\<username>\.my.cnf` in windows.

**Comment by steven-ysj** [comment] 2020-05-01 02:53
I have the same problem, and unfortunately i haven't found the solution to solve it.
Otherwise, the pgcli has the same problem on windows platform.
I think it's a bug, waiting for someone fix it.

**Comment by whm2015** [comment] 2020-05-28 15:01
I have the same problem too. I ckeck the log file (in windows is `C:\Users\<username>\.mycli.log`), but it didn't record anything related. The error dosen't have a traceback.
By the way, "系统找不到指定的文件" is "The system cannot find the file specified".

![image](https://user-images.githubusercontent.com/17809442/83141680-afe1eb00-a122-11ea-8c41-02ddbe75f408.png)

I found that if I comment the line 837 in main.py, the problem disappear.
https://github.com/dbcli/mycli/blob/7a059a6f9eea76af30966609bce8361de2c501ca/mycli/main.py#L837

Then I found this issue about click [echo_via_pager broken on Windows in 7.1](https://github.com/pallets/click/issues/1514). According to its solution, I upgrade the click from 7.1.1 to 7.1.2, and it works.

![image](https://user-images.githubusercontent.com/17809442/83156780-677ff880-a135-11ea-94d4-94b2b545a02c.png)
![image](https://user-images.githubusercontent.com/17809442/83156790-6949bc00-a135-11ea-9eb3-608d872880fc.png)
@amjith @luojianet @yuxingchang @steven-ysj

**Comment by whm2015** [comment] 2020-05-28 15:09
#854 May duplicate of this

**Comment by steven-ysj** [comment] 2020-05-31 10:43
@whm2015 Well Done.I just try it,and both mycli and pgcli perform properly.Thank you.

**Closed** 2021-02-25 20:42 UTC
