### ISSUE TITLE
Automatically format the code

### ISSUE THREAD

**Issue by amjith** [dbcli/mycli#392] opened 2017-04-04 04:36 UTC
Formatting code to comply with pep8 is a tedious task. We should have a bot that does that for us. 

Fortunately, there is a package that can automatically format python code. 

https://github.com/google/yapf

It would be nice to have this run as part of the pre-commit hook or at least in the pre-push hook.

**Comment by amjith** [comment] 2017-04-04 04:36
@dbcli/mycli-core What are your thoughts on this idea?

**Comment by meeuw** [comment] 2017-04-04 07:55
I really like the code to be uniformly formatted but I prefer a slow approach only on changed / new code.

If we reformat old code in one or multiple commits it will make the use of `git blame` less easy.

Another option might be to rewrite our master branch by using `git filter-branch` and yapf, breaking all forks/branches.

But maybe I'm exaggerating and it only applies to a few lines. 

I also like the suggestion from @tsroten to use CI/Travis for this purpose (only giving warnings).

**Comment by amjith** [comment] 2017-04-04 14:09
You make a good point about ruining `git blame` by running yapf. 

I hadn't heard of `git filter-branch`, but my initial research shows that it will rewrite the entire history and as you said it will invalidate all the forks and branches. 

I'm ok with taking an incremental approach. We can fix pep 8 violations as we touch code. 

Are we going to do strict pep8 or pep8 with exceptions? If so, do people have any config file that they use with exceptions?

**Comment by amjith** [comment] 2017-04-04 14:17
I just found out about pep8radius: https://pypi.python.org/pypi/pep8radius

It can apply an auto-formatter just to the lines that were touched. I can also use yapf as it's backend.

**Comment by meeuw** [comment] 2017-04-04 14:38
I LOVE the idea of pep8radius, great find!

**Comment by johnksterling** [comment] 2017-04-04 20:42
I agree that I don't like auto-reformatting, incremental FTW.  Once things are clean you can have the builds fail using pylint or the like to avoid future regressions.

**Comment by tsroten** [comment] 2017-04-05 00:27
pep8radius looks excellent. I think it sounds like this incremental approach is well received.

As far as exceptions go, if we're setting up builds to fail based on lint checking (in the future), we'll want to include the exception for line length. Not many projects follow a strict 79 character length limit in every circumstance. 79 characters is good almost all the time, but there are definitely scenarios that are tough to fit in the 79 character limit. If there is a strong reason not to and the team is in agreement, PEP8 allows up to 99 characters:

>> Some teams strongly prefer a longer line length. For code maintained exclusively or primarily by a team that can reach agreement on this issue, it is okay to increase the nominal line length from 80 to 100 characters (effectively increasing the maximum length to 99 characters), provided that comments and docstrings are still wrapped at 72 characters.

**Comment by johnksterling** [comment] 2017-04-05 00:37
I agree with the PEP8 allowance of <100.  That is what we generally follow.

**Comment by amjith** [comment] 2017-04-05 02:29
Would anyone be interested in setting up pep8radius on Travis CI?

**Comment by j-bennet** [comment] 2017-04-05 02:31
I'd like to.

**Comment by j-bennet** [comment] 2017-04-05 17:56
Looks like we can do it two ways:

1. Use git pre-push hooks (everyone has to set up his own hooks). More work for everyone, but less work for the repo maintainer.
2. Set up travis to run `pep8radius` for every PR, and if any code style problems are found, make a commit and push to correct those. This is more complicated to set up, since Travis has to be authenticated (use an auth token) to be able to push changes all by itself.

**Comment by meeuw** [comment] 2017-04-05 18:06
@j-bennet I think it would also be possible for Travis to give a warning/failure if an PR introduces/changes code which isn't PEP8 compliant, I don't like automated commits.

**Comment by j-bennet** [comment] 2017-04-06 23:47
Resolved by #395.

**Closed by j-bennet** 2017-04-06 23:47 UTC
Labels: enhancement
