### ISSUE TITLE
MYCLI does not work on WIndows 10

### ISSUE THREAD

**Issue by Bhavesh164** [dbcli/mycli#983] opened 2021-05-03 09:59 UTC
MYCLI gives error on connecting to windows 10
Python version: 3.8.0
PIp version: 3.21.1
 
It gives the following error
![image](https://user-images.githubusercontent.com/13777960/116863655-3e5cc780-ac24-11eb-9f54-1977f7e2124c.png)

I also try to connect using 
mycli -u root -h localhost -p your_password --database fleetio

But still getting the same error

**Comment by amjith** [comment] 2021-05-09 03:28
Duplicate of #978

**Closed by amjith** 2021-05-09 03:28 UTC
