### ISSUE TITLE
ON WINDOWS When I input the keyword choice after the completion of the keyword, press the space when submitted to the following error

### ISSUE THREAD

**Issue by jianglong1992** [dbcli/mycli#291] opened 2016-07-23 18:13 UTC
use

                                Exception in thread Thread-4:
Traceback (most recent call last):se
  File "C:\Python34\lib\threading.py", line 920, in _bootstrap_inner
    self.run()
  File "C:\Python34\lib\threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python34\lib\site-packages\prompt_toolkit\interface.py", line 835, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "C:\Python34\lib\site-packages\mycli-1.7.1-py3.4.egg\mycli\sqlcompleter.py", line 246, in get_completions
    suggestions = suggest_type(document.text, document.text_before_cursor)
  File "C:\Python34\lib\site-packages\mycli-1.7.1-py3.4.egg\mycli\packages\completion_engine.py", line 85, in suggest_type
    full_text, identifier)
  File "C:\Python34\lib\site-packages\mycli-1.7.1-py3.4.egg\mycli\packages\completion_engine.py", line 134, in suggest_based_on_last_token
    token_v = token.value.lower()
AttributeError: 'tuple' object has no attribute 'value'

**Comment by amjith** [comment] 2016-07-25 02:49
Interesting! Can you tell me what command you typed when this happened? 

Also is this issue reproducible?

**Comment by cpgo** [comment] 2016-07-25 19:20
Same issue here.
Using manjaro with python 3.5.1, installed pip via yaourt.
Like the title says, the error is thrown after I press the spacebar after entering `use` to change the database

**Comment by caorong** [comment] 2016-07-26 09:23
maybe because mysql server config with `no-auto-rehash` ?

**Comment by cpgo** [comment] 2016-07-26 11:04
@caorong I removed  the `no-auto-rehash` from `my.cnf` and it seems to be working now.
But that is funny because I have the exact same installation on 2 other machines and I never had to do this

**Comment by jianglong1992** [comment] 2016-07-26 14:16
I removed the no-auto-rehash but it's still not working

**Comment by jianglong1992** [comment] 2016-07-26 14:34
@amjith it happended every key words such as "use select show..."

**Comment by amjith** [comment] 2016-07-27 06:21
This was because I didn't pin the dependency of sqlparse and the latest version has broken everything. 😭 

I'll try and fix that. In the meantime you can downgrade your sqlparse version and continue to use. Downgrading is done as follows: 

```
pip install sqlparse==0.1.19
```

Sorry about that.

**Comment by linzeyang** [comment] 2016-07-29 17:03
Thanks @amjith, the downgrading way works for me.

**Comment by jianglong1992** [comment] 2016-07-30 03:30
@amjith  it works after I installed sqlparse ,thank you ..

**Comment by amjith** [comment] 2016-08-03 18:24
This is now fixed in version 1.8.0. Please upgrade mycli: 

```
pip install -U mycli
```

**Closed by amjith** 2016-08-03 18:24 UTC
