### ISSUE TITLE
show create table can not show full structure

### ISSUE THREAD

**Issue by woshizoufeng** [dbcli/mycli#731] opened 2019-04-11 04:03 UTC
mycli version: 1.19.0
Python 2.7.14
OS: CentOS release 6.8 (Final)

![image](https://user-images.githubusercontent.com/9295077/55929892-6948dd00-5c51-11e9-81e3-d31393f2ee94.png)

But, in my another machine,  mycli version, python, os is same. It work fine.

So confuse with me.

**Comment by chux0519** [comment] 2019-04-16 03:40
the same issue, on openSUSE Tumbleweed

python version: 2.7.15
mycli version: 1.19.0

> uname -r
> 5.0.5-1-default

**Comment by chux0519** [comment] 2019-04-16 03:45
> desc <table>

works

**Comment by meeuw** [comment] 2019-04-19 05:56
Thanks for reporting this! Could you please post a `CREATE TABLE` query to reproduce this issue? 
My guess is that it's related to the "double width" characters/glyphs that are visible in your screenshot so please include those. This is certainly a bug we need to fix.

**Comment by woshizoufeng** [comment] 2019-04-22 03:56
> Thanks for reporting this! Could you please post a `CREATE TABLE` query to reproduce this issue?
> My guess is that it's related to the "double width" characters/glyphs that are visible in your screenshot so please include those. This is certainly a bug we need to fix.

Sorry reply too late.

In mycli:
![image](https://user-images.githubusercontent.com/9295077/56482238-91f49080-64f5-11e9-8f49-b2940e3201b1.png)

SQL:
`CREATE TABLE `t_user_action_permission` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `qid` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '用户QID',
  `action_type` tinyint(2) unsigned NOT NULL DEFAULT '0' COMMENT '行为类型',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `expire_time` timestamp NOT NULL COMMENT '行为失效时间点',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_qid_act` (`qid`,`action_type`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4`

**Comment by meeuw** [comment] 2019-04-23 18:02
Right, I found it. This is intended functionality. For formatting purposes the maximum for these output formats is 500 characters:
https://github.com/dbcli/cli_helpers/blob/master/cli_helpers/tabular_output/output_formatter.py#L17

I'd suggest to use the wide output anyway by appending `\G`:
`SHOW CREATE TABLE t_user_action_permission\G`

What do you think @j-bennet ?

**Comment by j-bennet** [comment] 2019-04-24 01:29
Perhaps we should have different formatter settings for `SHOW` commands. The 500 character limit was added to speed things up, because formatting was very slow on tens of columns and hundreds of rows of text. This is not going to be the case for `SHOW TABLE` statements. I think we can make those unlimited, or set a very high limit.

**Comment by meeuw** [comment] 2019-04-24 18:03
Maybe we can change the character limit to max. x characters between newlines in a field?

**Comment by leolinf** [comment] 2019-04-26 02:36
I have the same problem

**Comment by j-bennet** [comment] 2019-04-26 02:50
Then we'll still get in trouble with fields that contain many lines of newline-separated text. I suppose we could also remedy that by limiting the number of lines in one field. But even if we do both of these changes, we are still not fixing the current problem, because here we have a field that has only one line of text, but it is longer than 500 characters.

**Comment by woshizoufeng** [comment] 2019-04-30 02:22
> Right, I found it. This is intended functionality. For formatting purposes the maximum for these output formats is 500 characters:
> https://github.com/dbcli/cli_helpers/blob/master/cli_helpers/tabular_output/output_formatter.py#L17
> 
> I'd suggest to use the wide output anyway by appending `\G`:
> `SHOW CREATE TABLE t_user_action_permission\G`
> 
> What do you think @j-bennet ?

Thanks for your reply, but some machine/OS is work fine for the same table, what's the reason?

**Comment by j-bennet** [comment] 2019-04-30 16:27
> Thanks for your reply, but some machine/OS is work fine for the same table, what's the reason?

So what is different between the two machines? You already said that mycli version, python version, and os is the same.

Is `pip freeze` output the same?

Are you using the same terminal app?

Are the terminal settings the same?

```
echo $COLUMNS
echo $LINES
echo $PAGER
```

**Comment by woshizoufeng** [comment] 2019-05-05 10:17
> > Thanks for your reply, but some machine/OS is work fine for the same table, what's the reason?
> 
> So what is different between the two machines? You already said that mycli version, python version, and os is the same.
> 
> Is `pip freeze` output the same?
> 
> Are you using the same terminal app?
> 
> Are the terminal settings the same?
> 
> ```
> echo $COLUMNS
> echo $LINES
> echo $PAGER
> ```

I use same terminal and setting. But pip freeze output is different. It's so hard to find the reason.
Thank's your reply. I use \G to make the work now.

**Comment by j-bennet** [comment] 2019-05-05 11:59
Can you attach the two `pip freeze` outputs (dumping them into text files might be easiest)?

**Comment by woshizoufeng** [comment] 2019-05-06 05:41
> Can you attach the two `pip freeze` outputs (dumping them into text files might be easiest)?

Yah, pls check the attach file. BTW, I find the pip version is different.
pip version(which mycli show fine): 10.0.1
pip version(which mycli show not fine): 19.0.3

[freeze_not_fine.txt](https://github.com/dbcli/mycli/files/3146466/freeze_not_fine.txt)
[freeze_fine.txt](https://github.com/dbcli/mycli/files/3146467/freeze_fine.txt)

**Comment by gaotuan** [comment] 2019-06-03 08:16
i alse  meet this problem.      i thank i can use \G   replace.    Thanks

**Comment by gscteam** [comment] 2019-06-06 14:32
same here on archlinux. It uses to work and after updates long lines are cut short.

**Comment by j-bennet** [comment] 2019-06-06 14:58
This was fixed in `cli_helpers` but not released yet:

https://github.com/dbcli/cli_helpers/pull/55

Until the release is out, you can install from master:

`pip install -U https://github.com/dbcli/cli_helpers/archive/master.zip`

**Comment by tsroten** [comment] 2019-06-10 11:41
Support for detecting multi-line strings during truncation was released in CLI Helpers 1.2.1.

You should be able to upgrade via: `pip install -U cli-helpers`.

Thanks for reporting this!

**Closed by tsroten** 2019-06-10 11:41 UTC
