### ISSUE TITLE
Pager not triggered

### ISSUE THREAD

**Issue by georgexsh** [dbcli/mycli#288] opened 2016-07-18 03:53 UTC
if table `foo` has 33 columns, type `desc foo` in a term which panel height is 40, pager will not be triggered, but the top most 8 lines not shown.
if panel resized to 39, paper will take over as expected.

retried reset `LESS` environ variable, not affected.

ps: runs inside a tmux session.

using mysli 1.7.1

**Comment by johnksterling** [comment] 2017-02-14 01:32
I reproduced this and was investigating resolving it.  I think it is caused because of the layers of tools being used to display the mycli console in a shell window.  It looked to me like it would be complicated to fix - and it isn't a very big pain point since it only happens when there is a small number of results.  I would vote for not fixing unless someone else sees an obvious way to work around it.

**Comment by tsroten** [comment] 2017-02-14 02:38
Hi @georgexsh! This is a combination of two things. First, mycli forces the less pager option `-F` which automatically causes the pager to quit if its contents can be displayed on one screen.

But, then the prompt toolkit we use to display the mycli prompt reserves extra blank lines at the bottom for the autocomplete functionality. You can see a related issue in a different app here: https://github.com/ipython/ipython/issues/9390

The easiest solution would probably be to allow users to override the less options that mycli uses. In other words, keep the current options (`-RXF`) as the default, but if the user specifies a config option, say `less_options`, then those will be used instead.

**Comment by dbolser-ebi** [comment] 2017-03-01 11:13
I have a related issue, I'd like the pager to be 'less -S' to "chop long lines". I'd also vote for a way to allow the pager to be customized.

**Comment by amjith** [comment] 2017-03-01 14:03
@dbolser-ebi You can configure the pager using `~/.my.cnf`. Here's what I have:

```
[client]
pager = 'less -XSRF'
```

This is `~/.my.cnf` NOT ~/.myclirc.

**Comment by johnksterling** [comment] 2017-03-01 14:12
I agree - that is what I do today.   It would be easy to also add a 'custom_pager_flags' configuration option that just over-rides the 'LESS' env variable with custom flags (they are hard-coded defaults today) - would there be any value in that?  I can spin up a PR for it if it sounds appealing for some reason.

**Comment by amjith** [comment] 2017-03-01 14:18
I'm reluctant to add more configuration options. I'm a big fan of the Fish shell's design documentation. http://fishshell.com/docs/current/design.html

In this case specifically we have two ways to in which we solve this, one we read the LESS env variable and use that unmodified if present, if it is not present then we use our own defaults. Two, we provide a way to completely override the pager with something else other than `less`. I think this should serve 99% of our users. I don't believe that adding a new option to just override the LESS options adds meaningful value. 

As always, I can be convinced otherwise. 😄

**Comment by tsroten** [comment] 2017-03-01 14:28
@amjith Good input.

Maybe I'm remembering incorrectly, but I thought that `mycli.configure_pager()` overrides the LESS environment variable instead of using it unmodified if it's present.

For example, I can't figure out a way to use LESS with mycli without the `-F` option -- mycli appears to force it on the user.

I agree with you that we shouldn't add another config option for this. I think in order to respect the existing environment variable for LESS (if there is one), we might need to make a small change to mycli to read first, then override if needed. Or, maybe I'm missing something here.

**Comment by johnksterling** [comment] 2017-03-01 15:32
That sounds reasonable.  I can look into that - i.e. if the less env is empty then make is sane.  If it has a value assume it is on purpose.  Thanks for the input.

**Comment by dbolser-ebi** [comment] 2017-03-01 16:43
Why no `pager = 'less -XSRF'` in .myclirc?

**Comment by tsroten** [comment] 2017-03-01 16:57
@dbolser-ebi I'm not sure if this is what you were suggesting:

If we don't even worry about the environment variable in mycli, we could simply rely on the default `myclirc` to set the pager to `less -RXF` (we took the `-S` option off [awhile go](https://github.com/dbcli/mycli/pull/237)). Then, if the user specifies a pager in their file (e.g. `less`), they'd be responsible for handling the options they might need.

So, in this specific issue, @georgexsh could set his pager to `less -RX`.

It has the benefit of -- simpler code (no environment variables to worry about) while providing a default behavior that is *easily* overridable.

Plus, it is more consistent because the included `myclirc` is how other defaults are specified (e.g. `smart_completion`, `multi_line`, etc.).

**Comment by tsroten** [comment] 2017-03-01 21:00
@dbolser-ebi Sorry for the confusion! In your `~/.my.cnf`, under the `[client]` section, type:
```
pager = "less -XSRF"
```

See if that works for you.

**Comment by amjith** [comment] 2017-03-01 23:31
I was under the impression that we were reading the `LESS` variable and checking to see if it already had some values and only setting them if it was empty. But I was wrong. Thanks for pointing that out @tsroten.

@johnksterling You're more than welcome to send a PR that checks if the `LESS` var is set and only override it if it is not set.

**Comment by dbolser-ebi** [comment] 2017-03-02 09:48
@tsroten I'm seeing the `mysqldump: unknown variable 'pager=less -XSRF'` error already mentioned in the context of prompt. I know this may seem like an edge case, but I routinely use mysqldump and mysqlcheck at work.

This seems to do the trick: `export LESS="less -SRF"`

**Comment by tsroten** [comment] 2017-03-02 14:20
@dbolser-ebi I think we'll definitely need to address that issue. I think we should use #281 for discussion about `.my.cnf` options clashing with the various official clients.

**Comment by tsroten** [comment] 2017-03-19 01:23
@georgexsh 

mycli version 1.9.0 is now out which should fix this. Your `LESS` environment variable will now be honored. You can install/upgrade by running `pip install --upgrade mycli`

Let us know if you run into any other issues, thanks!

**Closed by tsroten** 2017-03-19 01:23 UTC
Labels: enhancement, Next Release
