### ISSUE TITLE
In command line, when press 'enter' it outputs multi blank lines.

### ISSUE THREAD

**Issue by jinleileiking** [dbcli/mycli#142] opened 2015-09-01 04:59 UTC
```
mysql uWFL9Wg6159@10.36.253.127:yingjian_duin> 








Command Time: 0.000s
Format Time: 0.000s
mysql uWFL9Wg6159@10.36.253.127:yingjian_duin> 








Command Time: 0.000s
Format Time: 0.000s
mysql uWFL9Wg6159@10.36.253.127:yingjian_duin> 








Command Time: 0.000s
Format Time: 0.000s
mysql uWFL9Wg6159@10.36.253.127:yingjian_duin> 
```

There are a lot of blank lines . Is it ok ?

**Comment by amjith** [comment] 2015-09-01 07:07
Typically there should be only one blank line. It's odd that there are multiple blank lines. 

When you run a command such as `SELECT 1` does it have any blank lines between the resulting table and the 'Command Time'?

**Comment by jinleileiking** [comment] 2015-09-01 07:37
```
➜  store_db  mycli -uuWFL9Wg6159 -pPm3a64WROxgCqQxIO -h10.36.253.127 -P6159 -D yingjian_duin 
Version: 1.3.0
Chat: https://gitter.im/dbcli/mycli
Mail: https://groups.google.com/forum/#!forum/mycli-users
Home: http://mycli.net
Thanks to the contributor - Daniel Black
mysql uWFL9Wg6159@10.36.253.127:yingjian_duin> SELECT 1







+-----+
|   1 |
|-----|
|   1 |
+-----+
1 row in set
Command Time: 0.000s
Format Time: 0.000s
mysql uWFL9Wg6159@10.36.253.127:yingjian_duin> 
```

**Comment by jinleileiking** [comment] 2015-09-01 07:37
my env: tmux + zsh + terminator( solarized theme)

**Comment by jinleileiking** [comment] 2015-09-01 07:39
It seems this problem is connected to `ssh`,  

my env is sshed to the remote terminal, then run tmux, --> mycli .

**Comment by jinleileiking** [comment] 2015-09-01 07:40
use local env, there is no blank lines.

**Comment by amjith** [comment] 2015-09-01 07:48
Interesting. I just tried by ssh-ing into a vagrant box and opened tmux and launched mycli. 

I'm not able to reproduce the multiple blank lines issue. I wonder if this is a weird interaction with character encoding + shell settings. 

I don't think this is necessarily a bad thing functionally, but I agree this is jarring in an aesthetic sense.

**Comment by jinleileiking** [comment] 2015-09-01 08:34
```
➜  store_db  locale
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

I use zsh + oh~my~zsh..

**Comment by amjith** [comment] 2015-09-02 04:56
You've stumped me. I have no idea why this is different for the ssh session. I would suspect it is due to the terminal settings, but I can't reproduce it locally. 

It's not something that is harmful or impacts the performance or even wide spread. So unless you can debug this further, I'm going to close the issue for now.

**Closed by amjith** 2015-09-02 04:56 UTC

**Comment by jinleileiking** [comment] 2015-09-02 06:41
Ok. Poor me.

**Comment by jinleileiking** [comment] 2016-01-26 02:09
@amjith Can you give me a clue where the code that shows the result of command? I want to debug it by myself

**Comment by jinleileiking** [comment] 2016-01-26 02:21
`output_via_pager` will generate the blank lines.

**Comment by jinleileiking** [comment] 2016-01-26 02:22
`click.echo_via_pager` will generate the blank lines.

**Comment by jinleileiking** [comment] 2016-01-26 02:24
@amjith  `self.output(text)` instead of `click.echo_via_pager` will fix this bug.

**Comment by jinleileiking** [comment] 2016-01-26 02:24
main.py 572

**Comment by tsroten** [comment] 2016-01-26 12:10
@jinleileiking I'm stumped by those blank lines as well. mycli will soon support turning off the pager so mycli will use `self.output(text)` instead. You can see it here: https://github.com/dbcli/mycli/pull/219
