### ISSUE TITLE
History & Search feature is not working on 1.6.0

### ISSUE THREAD

**Issue by Sangdol** [dbcli/mycli#258] opened 2016-04-21 02:58 UTC
First of all, thank you for the great application.

After I upgraded to v1.6.0, `<C-r>` shortcut is not working anymore. It works well when I use v1.5.2. I read [changelog](https://github.com/dbcli/mycli/blob/master/changelog.md) but I couldn't find something related to this? Am I missing something?

**Comment by amjith** [comment] 2016-04-23 21:21
You're right this was broken in the latest release. I'll fix it soon.

**Comment by michaelstack** [comment] 2016-05-09 06:51
I have also noticed this has stopped working in vi mode with `ESC /<searchterm>`

@amjith I am guessing that you already fixed vi mode in https://github.com/dbcli/mycli/pull/259 ?

**Comment by amjith** [comment] 2016-05-09 07:01
Yes it is fixed. You can try it by installing directly from master as follows: 

```
pip install -U https://github.com/dbcli/mycli/archive/master.zip
```

**Comment by michaelstack** [comment] 2016-05-10 00:20
@amjith I installed from master. I can confirm that it is working for me again. 

Thanks.

**Comment by tsroten** [comment] 2017-03-18 01:42
I'm closing this issue since it was released in version 1.7.0.

**Closed by tsroten** 2017-03-18 01:42 UTC

**Comment by Sangdol** [comment] 2017-03-18 12:04
Great thanks!
